// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import Todos__TasksController from "./todos/tasks_controller"
application.register("todos--tasks", Todos__TasksController)

import TurboController from "./turbo_controller"
application.register("turbo", TurboController)
